### PR TITLE
added server based hiscores

### PR DESCRIPTION
**Pull request by sbrother**

### CODE REVIEW

**Comment by Kovak** [comment]
This does not currently run on my computer and produces the error:

   File "main.py", line 1593, in <module>
     RunningGameApp().run()
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/app.py", line 542, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/base.py", line 421, in runTouchApp
     p = provider(key, args)
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 116, in **new**
     instance.**init**(device, args)
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 153, in **init**
     self.probe()
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 159, in probe
     x.has_capability(ABS_MT_POSITION_X)]
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 89, in has_capability
     capabilities = self.get_capabilities()
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 80, in get_capabilities
     long_bit = getconf("LONG_BIT")
   File "/usr/local/lib/python2.7/dist-packages/Kivy-1.4.1-py2.7-linux-x86_64.egg/kivy/input/providers/probesysfs.py", line 93, in getconf
     output = Popen(["getconf", var], stdout=PIPE).communicate()[0]
   File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
     raise child_exception
 OSError: [Errno 9] Bad file descriptor

This is not necessarily a huge issue if it does in fact work on android, could you email out an apk of this branch if that is the case so I can test.

**Comment by sbrother** [comment]
Very strange - those errors seem to be happening in base kivy files, not in our code. it runs fine on my mac and also on my ubuntu machine. Kerby, can you test?

**Comment by KerbySmith** [comment]
I am at Lange right now but I pulled down the branch and it is running fine
on Windows.
Kerby

**Comment by cooper51** [comment]
Perhaps the app does not have permission to use the internet.

**Pull request closed without merging**
